language: node_js

cache:
  directories:
    - node_modules

node_js:
  - '7'
  - '6'

before_script:
  - npm prune

script:
  - npm run cover

after_success:
  - npm run coveralls
  - npm run semantic-release

branches:
  except:
    - /^v\d+\.\d+\.\d+$/
